"use strict";

window.MOCK_DATA = Object.freeze({

  CANONICAL_VALUES: {
    level: {
      beginner: "Beginner",
      independent: "Independent",
      advanced: "Advanced"
    },
    water: {
      flat: "Flat",
      chop_light: "Chop light",
      chop: "Chop",
      chop_strong: "Chop strong",
      small_waves: "Small waves",
      waves: "Waves",
      big_waves: "Big waves"
    },
    result: {
      underpowered: "Underpowered",
      good: "Good",
      powered: "Powered",
      overpowered: "Overpowered",
      survival: "Survival"
    },
    board: {
      twintip: "Twintip",
      surfboard: "Surfboard",
      foil: "Foil"
    },
    gender: {
      M: "Male",
      F: "Female"
    }
  },

  BRAND_LIST: [
    "Airush", "Best", "Cabrinha", "CrazyFly", "Duotone Kiteboarding",
    "Eleveight", "Core Kiteboarding", "F-One", "Flysurfer", "Gaastra Kiteboarding",
    "Harlem Kitesurfing", "Liquid Force", "Naish Kiteboarding", "Nobile Kiteboarding",
    "Ocean Rodeo", "North Kiteboarding", "Ozone", "RRD", "Slingshot"
    ,
    "AJ",
    "Bali Hai Kiteboards",
    "Ben Wilson Surf",
    "Blade",
    "Brunotti",
    "Cali",
    "Calibro 9",
    "Dakine",
    "Flexifoil",
    "Genetrix",
    "Genetrix Kiteboarding",
    "GUNSAILS",
    "HQ",
    "HQ Powerkites",
    "ION",
    "Jimmy Lewis",
    "Kaack",
    "Kazuma",
    "KSP",
    "KSP Sports",
    "Mystic",
    "NeilPryde",
    "Peter Lynn",
    "Prolimit"
  ],

  MODELS_BY_BRAND: {
    "Airush": [
      "Ultra v5",
      "Ultra Team DS v5",
      "Lithium v14",
      "Lithium Team v14",
      "Lift v3",
      "Lift Kite v4",
      "Lift Team v4",
      "Razor v10",
      "Session v2",
      "Session Team v2",
      "Lithium v13",
      "Lithium Team v13",
      "Drifter",
      "Fundamental",
      "Lift",
      "Lift Team",
      "Lithium",
      "Mach",
      "Razor",
      "Razor Team",
      "Relax",
      "Reo",
      "Session",
      "Thrust",
      "Torch",
      "Ultra",
      "Ultra Team",
      "Union",
      "Union Team",
      "Wing"
    ],
    "Best": [
      "AYRA",
      "ROCA",
      "HEX",
      "SWOX",
      "JET",
      "STORM",
      "ZEPHYR",
      "TRIO",
      "AYRA Ultralight"
    ],
    "Cabrinha": [
      "Switchblade",
      "Switchblade Apex",
      "Moto",
      "Nitro",
      "Nitro Apex",
      "Drifter",
      "Drifter Apex",
      "Moto X",
      "Moto X Lite",
      "Moto XL",
      "Moto XL Apex",
      "FX",
      "FX2",
      "Contra"
    ],
    "CrazyFly": [
      "Sculp",
      "Hyper",
      "Nuke"
    ],
    "Duotone Kiteboarding": [
      "Evo",
      "Evo SLS / D-Lab",
      "Evo SLS",
      "Evo D/Lab",
      "Evo Concept Blue",
      "Rebel",
      "Rebel SLS / D-Lab",
      "Rebel SLS",
      "Rebel D/Lab",
      "Neo",
      "Neo SLS",
      "Neo D/Lab",
      "Dice",
      "Juice",
      "Juice Dlab",
      "Juice D/Lab",
      "Vegas",
      "Vegas Concept Blue",
      "Vegas D/Lab",
      "Mono",
      "Volt",
      "Volt D/Lab",
      "Gonzales"
    ],
    "Eleveight": [
      "RS V9",
      "RS+ V3",
      "RS Pro 2025",
      "FS V8",
      "XS V5",
      "WS V8",
      "PS V8"
    ],
    "Core Kiteboarding": [
      "XR",
      "XR5",
      "XR6",
      "XR7",
      "XR8",
      "XR8 LW",
      "XR Pro",
      "XR Pro 2",
      "Nexus",
      "Nexus 2",
      "Nexus 3",
      "Nexus 4",
      "Nexus LW",
      "GTS",
      "Pace",
      "Pace Pro",
      "Section",
      "Section 2",
      "Section 3",
      "Section 4",
      "Section 5",
      "Section LW",
      "GTS5",
      "GTS6",
      "GTS6 LW",
      "Xlite",
      "Xlite 2",
      "Impact",
      "Impact 2",
      "Xperience",
      "Air",
      "Air Pro",
      "Badger Pro",
      "Nexus 4 LW"
    ],
    "F-One": [
      "Bandit",
      "Bandit TEC",
      "Bandit XV",
      "Bandit S",
      "Bandit-S",
      "Breeze",
      "Bullit",
      "Diablo",
      "Addikt",
      "Chrono Foil",
      "Trax Foil",
      "Cobra Foil",
      "Kyankka Foil"
    ],
    "Flysurfer": [
      "Era",
      "Era 2",
      "Speed3",
      "Peak3",
      "Soul3",
      "Hybrid",
      "Hybrid²",
      "Indie",
      "Hybrid2"
    ],
    "Gaastra Kiteboarding": [
      "Spark",
      "Pure",
      "One",
      "Max",
      "IQ"
    ],
    "Harlem Kitesurfing": [
      "Thrive",
      "Peak",
      "Hadlow Pro",
      "Force"
    ],
    "Liquid Force": [
      "NV",
      "NV V8",
      "NV V9",
      "Solo",
      "WOW V3",
      "WOW V4",
      "Recon",
      "Momentum",
      "Testament",
      "Trinity",
      "WOW"
    ],
    "Naish Kiteboarding": [
      "Pivot",
      "Pivot Nvision",
      "Triad",
      "Psycho",
      "Dash",
      "Ride",
      "Slash",
      "Boxer",
      "Torch"
    ],
    "Nobile Kiteboarding": [
      "Childhood",
      "Childhood Light",
      "Peanut",
      "Peanut Light",
      "Freedom",
      "Maverick",
      "Scrap",
      "Step",
      "Squirt",
      "Squirt Light"
    ],
    "Ocean Rodeo": [
      "Flite A-Series",
      "Prodigy",
      "Razor",
      "Roam",
      "Crave",
      "Rise 5"
    ],
    "North Kiteboarding": [
      "Reach",
      "Orbit",
      "Orbit Pro",
      "Orbit Ultra",
      "Carve",
      "Pulse",
      "Code Zero",
      "Code Zero Pro"
    ],
    "Ozone": [
      "Enduro",
      "Edge",
      "Alpha",
      "Catalyst",
      "Vortex",
      "AMP",
      "Reo",
      "Zephyr",
      "Zephyr Ultra-X",
      "Chrono",
      "Chrono V5",
      "Hyperlink"
    ],
    "RRD": [
      "Addiction",
      "Emotion",
      "Obsession",
      "Obsession Gold",
      "Passion",
      "Passion Y30",
      "Religion",
      "Passion LW Y30",
      "Vision",
      "Vision Y27",
      "Religion Y30"
    ],
    "Slingshot": [
      "Rally GT",
      "Code",
      "Code V2",
      "Code NXT",
      "Rally",
      "Ghost",
      "Ghost V3",
      "SST",
      "UFO",
      "RPM",
      "RPX",
      "Mistral"
    ],
    "AJ": [],
    "Bali Hai Kiteboards": [],
    "Ben Wilson Surf": [],
    "Blade": [],
    "Brunotti": [],
    "Cali": [],
    "Calibro 9": [],
    "Dakine": [],
    "Flexifoil": [],
    "Genetrix": [],
    "Genetrix Kiteboarding": [],
    "GUNSAILS": [],
    "HQ": [],
    "HQ Powerkites": [],
    "ION": [],
    "Jimmy Lewis": [],
    "Kaack": [],
    "Kazuma": [],
    "KSP": [],
    "KSP Sports": [],
    "Mystic": [],
    "NeilPryde": [],
    "Peter Lynn": [],
    "Prolimit": []
  },

  BOARD_SIZE_BY_TYPE: {
    twintip: [
      "125x38", "129x38", "130x39", "132x39", "133x39", "133x40",
      "134x39", "134x40", "135x40", "136x40", "136x40.5", "137x40",
      "137x40.5",
      "137x41", "138x41",
      "138x42", "139x41", "139x42", "140x41", "140x42", "141x41",
      "141x42",
      "142x42", "144x41.5", "144x44", "145x43", "146x43", "147x44",
      "148x45", "150x45", "150x46", "160x45", "160x46"
    ],
    surfboard: [
      "5'0", "5'1", "5'2", "5'3", "5'4", "5'5", "5'6", "5'7", "5'8",
      "5'9", "5'10", "5'11", "6'0", "6'1", "6'2", "6'3", "6'4"
    ],
    foil: [
      "50", "60", "65", "70", "75", "80", "85", "90", "95", "100",
      "104", "110", "120", "130", "140", "150"
    ]
  }

});
