-- CATALOG ENGINE / backend-ready / TEST locale
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;
DROP TABLE IF EXISTS catalog_engine_kites;
CREATE TABLE catalog_engine_kites (
    catalog_id INTEGER PRIMARY KEY AUTOINCREMENT,
    brand TEXT,
    model TEXT,
    series TEXT,
    year_raw TEXT,
    year_start INTEGER,
    year_end INTEGER,
    discipline TEXT,
    catalog_scope TEXT,
    general_guardrail_ok INTEGER,
    size_m2 REAL,
    kite_weight_kg REAL,
    wind_min_kts REAL,
    wind_max_kts REAL,
    source_type TEXT,
    source_url TEXT,
    backend_use TEXT,
    note TEXT,
    wind_mid_kts REAL GENERATED ALWAYS AS ((wind_min_kts + wind_max_kts) / 2.0) VIRTUAL,
    wind_range_kts REAL GENERATED ALWAYS AS (wind_max_kts - wind_min_kts) VIRTUAL
);
CREATE INDEX idx_catalog_engine_kites_brand_model_size ON catalog_engine_kites(brand, model, size_m2);
CREATE INDEX idx_catalog_engine_kites_guardrail ON catalog_engine_kites(general_guardrail_ok, backend_use);
CREATE INDEX idx_catalog_engine_kites_wind ON catalog_engine_kites(wind_min_kts, wind_max_kts);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('CORE', 'Nexus 4', 'Universal+', '2024-', 2024, NULL, 'Wave + / Freestyle / Freeride', 'general_or_mixed', 'yes', 5, 1.9, 22, 42, 'official', 'https://store.ridecore.com/products/nexus-4', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('CORE', 'Nexus 4', 'Universal+', '2024-', 2024, NULL, 'Wave + / Freestyle / Freeride', 'general_or_mixed', 'yes', 6, 2.2, 20, 38, 'official', 'https://store.ridecore.com/products/nexus-4', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Duotone', 'Evo SLS', 'Allround', '2020-', 2020, NULL, 'Freeride / Freestyle / Wave', 'general_or_mixed', 'yes', 7, 2.3, 18, 38, 'official', 'https://www.duotonesports.com/it/ch/products/duotone-evo-sls-2024-44240-3013', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Duotone', 'Evo SLS', 'Allround', '2020-', 2020, NULL, 'Freeride / Freestyle / Wave', 'general_or_mixed', 'yes', 8, 2.5, 16, 36, 'official', 'https://www.duotonesports.com/it/ch/products/duotone-evo-sls-2024-44240-3013', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Duotone', 'Juice 2024', 'Lightwind / Foil', '2024-', 2024, NULL, 'Lightwind / Foil', 'specialized_lightwind_foil', 'no', 14, 3.08, 10, 18, 'retailer', 'https://www.skymonster.com/products/duotone-juice-2024', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Duotone', 'Juice 2024', 'Lightwind / Foil', '2024-', 2024, NULL, 'Lightwind / Foil', 'specialized_lightwind_foil', 'no', 15, 3.43, 10, 18, 'retailer', 'https://www.skymonster.com/products/duotone-juice-2024', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Duotone', 'Juice 2024', 'Lightwind / Foil', '2024-', 2024, NULL, 'Lightwind / Foil', 'specialized_lightwind_foil', 'no', 17, 3.63, 10, 18, 'retailer', 'https://www.skymonster.com/products/duotone-juice-2024', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Duotone', 'Neo SLS', 'Wave', '2020-', 2020, NULL, 'Wave / Freeride', 'general_or_mixed', 'yes', 4, 1.94, 24, 40, 'retailer', 'https://www.coronation-industries.de/shop/en/duotone-kites/22503-duotone-neo-sls-2024-kite-test-9m.html', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Duotone', 'Neo SLS', 'Wave', '2020-', 2020, NULL, 'Wave / Freeride', 'general_or_mixed', 'yes', 5, 2.11, 20, 37, 'retailer', 'https://www.coronation-industries.de/shop/en/duotone-kites/22503-duotone-neo-sls-2024-kite-test-9m.html', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Duotone', 'Neo SLS', 'Wave', '2020-', 2020, NULL, 'Wave / Freeride', 'general_or_mixed', 'yes', 6, 2.33, 18, 35, 'retailer', 'https://www.coronation-industries.de/shop/en/duotone-kites/22503-duotone-neo-sls-2024-kite-test-9m.html', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Duotone', 'Neo SLS', 'Wave', '2020-', 2020, NULL, 'Wave / Freeride', 'general_or_mixed', 'yes', 7, 2.45, 16, 33, 'retailer', 'https://www.coronation-industries.de/shop/en/duotone-kites/22503-duotone-neo-sls-2024-kite-test-9m.html', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Duotone', 'Rebel SLS', 'Big Air / Freeride', '2020-', 2020, NULL, 'Big Air / Freeride', 'general_or_mixed', 'yes', 6, 2.44, 21, 40, 'retailer', 'https://www.versusshop.nl/en/shop/duotone-rebel-sls-2026-156602', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Duotone', 'Rebel SLS', 'Big Air / Freeride', '2020-', 2020, NULL, 'Big Air / Freeride', 'general_or_mixed', 'yes', 7, 2.65, 19, 38, 'retailer', 'https://www.versusshop.nl/en/shop/duotone-rebel-sls-2026-156602', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Duotone', 'Rebel SLS', 'Big Air / Freeride', '2020-', 2020, NULL, 'Big Air / Freeride', 'general_or_mixed', 'yes', 8, 2.84, 17, 36, 'retailer', 'https://www.versusshop.nl/en/shop/duotone-rebel-sls-2026-156602', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Peak', 'Big Air', '2025-2026', 2025, 2026, 'Big Air / Freeride', 'general_or_mixed', 'yes', 6, 2.19, 28, 44, 'official', 'https://harlemkitesurfing.com/products/harlem-peak', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Peak', 'Big Air', '2025-2026', 2025, 2026, 'Big Air / Freeride', 'general_or_mixed', 'yes', 7, 2.36, 25, 41, 'official', 'https://harlemkitesurfing.com/products/harlem-peak', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Peak', 'Big Air', '2025-2026', 2025, 2026, 'Big Air / Freeride', 'general_or_mixed', 'yes', 8, 2.48, 23, 38, 'official', 'https://harlemkitesurfing.com/products/harlem-peak', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Peak', 'Big Air', '2025-2026', 2025, 2026, 'Big Air / Freeride', 'general_or_mixed', 'yes', 9, 2.64, 19, 34, 'official', 'https://harlemkitesurfing.com/products/harlem-peak', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Peak', 'Big Air', '2025-2026', 2025, 2026, 'Big Air / Freeride', 'general_or_mixed', 'yes', 10, 2.84, 16, 32, 'official', 'https://harlemkitesurfing.com/products/harlem-peak', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Peak', 'Big Air', '2025-2026', 2025, 2026, 'Big Air / Freeride', 'general_or_mixed', 'yes', 11, 2.98, 15, 29, 'official', 'https://harlemkitesurfing.com/products/harlem-peak', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Peak', 'Big Air', '2025-2026', 2025, 2026, 'Big Air / Freeride', 'general_or_mixed', 'yes', 12, 3.15, 14, 26, 'official', 'https://harlemkitesurfing.com/products/harlem-peak', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Thrive', 'Allround', '2024-2025', 2024, 2025, 'Allround / Big Air / Freeride', 'general_or_mixed', 'yes', 5, 1.65, 24, 45, 'retailer', 'https://www.mackiteboarding.com/harlem-thrive-kiteboarding-kite/', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Thrive', 'Allround', '2024-2025', 2024, 2025, 'Allround / Big Air / Freeride', 'general_or_mixed', 'yes', 6, 1.8, 23, 41, 'retailer', 'https://www.mackiteboarding.com/harlem-thrive-kiteboarding-kite/', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Thrive', 'Allround', '2024-2025', 2024, 2025, 'Allround / Big Air / Freeride', 'general_or_mixed', 'yes', 7, 1.91, 21, 38, 'retailer', 'https://www.mackiteboarding.com/harlem-thrive-kiteboarding-kite/', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Thrive', 'Allround', '2024-2025', 2024, 2025, 'Allround / Big Air / Freeride', 'general_or_mixed', 'yes', 8, 2.14, 19, 35, 'retailer', 'https://www.mackiteboarding.com/harlem-thrive-kiteboarding-kite/', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Thrive', 'Allround', '2024-2025', 2024, 2025, 'Allround / Big Air / Freeride', 'general_or_mixed', 'yes', 9, 2.3, 17, 31, 'retailer', 'https://www.mackiteboarding.com/harlem-thrive-kiteboarding-kite/', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Thrive', 'Allround', '2024-2025', 2024, 2025, 'Allround / Big Air / Freeride', 'general_or_mixed', 'yes', 10, 2.45, 15, 29, 'retailer', 'https://www.mackiteboarding.com/harlem-thrive-kiteboarding-kite/', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Thrive', 'Allround', '2024-2025', 2024, 2025, 'Allround / Big Air / Freeride', 'general_or_mixed', 'yes', 11, 2.67, 14, 26, 'retailer', 'https://www.mackiteboarding.com/harlem-thrive-kiteboarding-kite/', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Thrive', 'Allround', '2024-2025', 2024, 2025, 'Allround / Big Air / Freeride', 'general_or_mixed', 'yes', 12, 2.74, 13, 23, 'retailer', 'https://www.mackiteboarding.com/harlem-thrive-kiteboarding-kite/', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Thrive', 'Allround', '2024-2025', 2024, 2025, 'Allround / Big Air / Freeride', 'general_or_mixed', 'yes', 13, 2.89, 12, 20, 'retailer', 'https://www.mackiteboarding.com/harlem-thrive-kiteboarding-kite/', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Thrive', 'Allround', '2024-2025', 2024, 2025, 'Allround / Big Air / Freeride', 'general_or_mixed', 'yes', 15, 3.24, 11, 18, 'retailer', 'https://www.mackiteboarding.com/harlem-thrive-kiteboarding-kite/', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('Harlem', 'Thrive', 'Allround', '2024-2025', 2024, 2025, 'Allround / Big Air / Freeride', 'general_or_mixed', 'yes', 17, 3.55, 9, 16, 'retailer', 'https://www.mackiteboarding.com/harlem-thrive-kiteboarding-kite/', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Carve', 'Allround', '2022-2024', 2022, 2024, 'Surf / Strapless Freestyle', 'specialized_wave', 'no', 3, NULL, 26, 40, 'retailer', 'https://www.mackiteboarding.com/2022-north-carve-kiteboarding-kite', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Carve', 'Allround', '2022-2024', 2022, 2024, 'Surf / Strapless Freestyle', 'specialized_wave', 'no', 4, NULL, 24, 38, 'retailer', 'https://www.mackiteboarding.com/2022-north-carve-kiteboarding-kite', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Carve', 'Allround', '2022-2024', 2022, 2024, 'Surf / Strapless Freestyle', 'specialized_wave', 'no', 5, NULL, 22, 36, 'retailer', 'https://www.mackiteboarding.com/2022-north-carve-kiteboarding-kite', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Carve', 'Allround', '2022-2024', 2022, 2024, 'Surf / Strapless Freestyle', 'specialized_wave', 'no', 6, NULL, 20, 34, 'retailer', 'https://www.mackiteboarding.com/2022-north-carve-kiteboarding-kite', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Carve', 'Allround', '2022-2024', 2022, 2024, 'Surf / Strapless Freestyle', 'specialized_wave', 'no', 7, NULL, 18, 32, 'retailer', 'https://www.mackiteboarding.com/2022-north-carve-kiteboarding-kite', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Carve', 'Allround', '2022-2024', 2022, 2024, 'Surf / Strapless Freestyle', 'specialized_wave', 'no', 8, NULL, 16, 30, 'retailer', 'https://www.mackiteboarding.com/2022-north-carve-kiteboarding-kite', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Carve', 'Allround', '2022-2024', 2022, 2024, 'Surf / Strapless Freestyle', 'specialized_wave', 'no', 9, NULL, 14, 28, 'retailer', 'https://www.mackiteboarding.com/2022-north-carve-kiteboarding-kite', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Carve', 'Allround', '2022-2024', 2022, 2024, 'Surf / Strapless Freestyle', 'specialized_wave', 'no', 10, NULL, 12, 26, 'retailer', 'https://www.mackiteboarding.com/2022-north-carve-kiteboarding-kite', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Carve', 'Allround', '2022-2024', 2022, 2024, 'Surf / Strapless Freestyle', 'specialized_wave', 'no', 11, NULL, 11, 24, 'retailer', 'https://www.mackiteboarding.com/2022-north-carve-kiteboarding-kite', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Carve', 'Allround', '2022-2024', 2022, 2024, 'Surf / Strapless Freestyle', 'specialized_wave', 'no', 12, NULL, 10, 22, 'retailer', 'https://www.mackiteboarding.com/2022-north-carve-kiteboarding-kite', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Carve', 'Allround', '2022-2024', 2022, 2024, 'Surf / Strapless Freestyle', 'specialized_wave', 'no', 14, NULL, 9, 20, 'retailer', 'https://www.mackiteboarding.com/2022-north-carve-kiteboarding-kite', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Orbit', 'Pro', '2022', 2022, 2022, 'Big Air / Freeride', 'general_or_mixed', 'yes', 5, NULL, 23, 38, 'retailer', 'https://www.nykitecenter.com/products/2022-north-orbit-kitesurfing-kite', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Orbit', 'Pro', '2022', 2022, 2022, 'Big Air / Freeride', 'general_or_mixed', 'yes', 6, NULL, 21, 37, 'retailer', 'https://www.nykitecenter.com/products/2022-north-orbit-kitesurfing-kite', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Orbit', 'Pro', '2022', 2022, 2022, 'Big Air / Freeride', 'general_or_mixed', 'yes', 7, NULL, 19, 36, 'retailer', 'https://www.nykitecenter.com/products/2022-north-orbit-kitesurfing-kite', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Orbit', 'Pro', '2022', 2022, 2022, 'Big Air / Freeride', 'general_or_mixed', 'yes', 8, NULL, 17, 35, 'retailer', 'https://www.nykitecenter.com/products/2022-north-orbit-kitesurfing-kite', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Orbit', 'Pro', '2022', 2022, 2022, 'Big Air / Freeride', 'general_or_mixed', 'yes', 9, NULL, 15, 32, 'retailer', 'https://www.nykitecenter.com/products/2022-north-orbit-kitesurfing-kite', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Orbit', 'Pro', '2022', 2022, 2022, 'Big Air / Freeride', 'general_or_mixed', 'yes', 10, NULL, 13, 29, 'retailer', 'https://www.nykitecenter.com/products/2022-north-orbit-kitesurfing-kite', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Orbit', 'Pro', '2022', 2022, 2022, 'Big Air / Freeride', 'general_or_mixed', 'yes', 11, NULL, 12, 27, 'retailer', 'https://www.nykitecenter.com/products/2022-north-orbit-kitesurfing-kite', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Orbit', 'Pro', '2022', 2022, 2022, 'Big Air / Freeride', 'general_or_mixed', 'yes', 12, NULL, 10, 25, 'retailer', 'https://www.nykitecenter.com/products/2022-north-orbit-kitesurfing-kite', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Orbit', 'Pro', '2022', 2022, 2022, 'Big Air / Freeride', 'general_or_mixed', 'yes', 14, NULL, 8, 22, 'retailer', 'https://www.nykitecenter.com/products/2022-north-orbit-kitesurfing-kite', 'ACTIVE_guardrail_general', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Pulse', 'Allround', '2025', 2025, 2025, 'Freestyle / Wakestyle', 'specialized_wakestyle', 'no', 4, NULL, 22, 36, 'retailer', 'https://www.kitemana.com/north/pulse-2025-kite-107801', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Pulse', 'Allround', '2025', 2025, 2025, 'Freestyle / Wakestyle', 'specialized_wakestyle', 'no', 5, NULL, 20, 34, 'retailer', 'https://www.kitemana.com/north/pulse-2025-kite-107801', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Pulse', 'Allround', '2025', 2025, 2025, 'Freestyle / Wakestyle', 'specialized_wakestyle', 'no', 6, NULL, 18, 32, 'retailer', 'https://www.kitemana.com/north/pulse-2025-kite-107801', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Pulse', 'Allround', '2025', 2025, 2025, 'Freestyle / Wakestyle', 'specialized_wakestyle', 'no', 7, NULL, 16, 30, 'retailer', 'https://www.kitemana.com/north/pulse-2025-kite-107801', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Pulse', 'Allround', '2025', 2025, 2025, 'Freestyle / Wakestyle', 'specialized_wakestyle', 'no', 8, NULL, 14, 28, 'retailer', 'https://www.kitemana.com/north/pulse-2025-kite-107801', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Pulse', 'Allround', '2025', 2025, 2025, 'Freestyle / Wakestyle', 'specialized_wakestyle', 'no', 9, NULL, 12, 26, 'retailer', 'https://www.kitemana.com/north/pulse-2025-kite-107801', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Pulse', 'Allround', '2025', 2025, 2025, 'Freestyle / Wakestyle', 'specialized_wakestyle', 'no', 10, NULL, 10, 24, 'retailer', 'https://www.kitemana.com/north/pulse-2025-kite-107801', 'ACTIVE_guardrail_specialized', 'retailer source');
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Reach', 'Allround', '2022-2025', 2022, 2025, 'Performance Freeride', 'general_or_mixed', 'yes', 5, NULL, 22, 37, 'official', 'https://northactionsports.com/products/reach-kite-2025', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Reach', 'Allround', '2022-2025', 2022, 2025, 'Performance Freeride', 'general_or_mixed', 'yes', 6, NULL, 20, 34, 'official', 'https://northactionsports.com/products/reach-kite-2025', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Reach', 'Allround', '2022-2025', 2022, 2025, 'Performance Freeride', 'general_or_mixed', 'yes', 7, NULL, 18, 32, 'official', 'https://northactionsports.com/products/reach-kite-2025', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Reach', 'Allround', '2022-2025', 2022, 2025, 'Performance Freeride', 'general_or_mixed', 'yes', 8, NULL, 16, 30, 'official', 'https://northactionsports.com/products/reach-kite-2025', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Reach', 'Allround', '2022-2025', 2022, 2025, 'Performance Freeride', 'general_or_mixed', 'yes', 9, NULL, 14, 28, 'official', 'https://northactionsports.com/products/reach-kite-2025', 'ACTIVE_guardrail_general', NULL);
INSERT INTO catalog_engine_kites (brand, model, series, year_raw, year_start, year_end, discipline, catalog_scope, general_guardrail_ok, size_m2, kite_weight_kg, wind_min_kts, wind_max_kts, source_type, source_url, backend_use, note) VALUES ('North', 'Reach', 'Allround', '2022-2025', 2022, 2025, 'Performance Freeride', 'general_or_mixed', 'yes', 10, NULL, 12, 26, 'official', 'https://northactionsports.com/products/reach-kite-2025', 'ACTIVE_guardrail_general', NULL);
COMMIT;